version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: knowledge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: knowledge_user
      POSTGRES_PASSWORD: knowledge_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      # データ永続化
      - postgres_data:/var/lib/postgresql/data
      # 初期化スクリプト（既存ダンプをリストア）
      - ../knowledge_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - /home/ubuntu01/java_knowledge_dump_backup.sql:/docker-entrypoint-initdb.d/02_data.sql
      # 設定ファイル
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - knowledge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knowledge_user -d knowledge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (データベース管理UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: knowledge-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@knowledge.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - knowledge-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  knowledge-network:
    driver: bridge